### ISSUE TITLE
Alternate RSS feed doesn't parse

### ISSUE THREAD

**Issue by brentonv** [ratul16/mediumApiCall#2]
I really love this as it doesn't require any external JavaScript and works with the different feeds I've tested except UptimeRobot RSS and I just can't figure out why.

I do understand you wrote this for Medium but could you please explain why this RSS feed doesn't parse with your code? https://api.rss2json.com/v1/api.json?rss_url=https://rss.uptimerobot.com/u1547170-7f480a74203d142f1ed154a4b64ce5cb

Thanks

**Comment by ratul16** [comment]
I am not sure what problem you faced, but it worked for me.

```js
fetch('https://api.rss2json.com/v1/api.json?rss_url=https://rss.uptimerobot.com/u1547170-7f480a74203d142f1ed154a4b64ce5cb')
  .then((res) => res.json())
  .then(data => {
  data.items.forEach(key => console.log(key.title))
})
```

**Comment by ratul16** [comment]
> I really love this as it doesn't require any external JavaScript and works with the different feeds I've tested except UptimeRobot RSS and I just can't figure out why.
> 
> I do understand you wrote this for Medium but could you please explain why this RSS feed doesn't parse with your code? https://api.rss2json.com/v1/api.json?rss_url=https://rss.uptimerobot.com/u1547170-7f480a74203d142f1ed154a4b64ce5cb
> 
> Thanks

I am not sure what problem you faced, but it worked for me.

```js
fetch('https://api.rss2json.com/v1/api.json?rss_url=https://rss.uptimerobot.com/u1547170-7f480a74203d142f1ed154a4b64ce5cb')
  .then((res) => res.json())
  .then(data => {
  data.items.forEach(key => console.log(key.title))
})
```

**Comment by brentonv** [comment]
Hi @ratul16 thanks for replying, I've attached some screenshots to better explain what's happening and hopefully you can tell me what I'm doing wrong?

https://medium.com/feed/@ratul16
![example1](https://user-images.githubusercontent.com/2313757/206842910-18df8ac5-6e41-4976-bce7-3f7adcde4cbe.png)

https://www.feedforall.com/sample.xml
![example2](https://user-images.githubusercontent.com/2313757/206842908-591c8dbb-7886-4748-ae4d-d790599a3adb.png)

http://rss.uptimerobot.com/u1547170-7f480a74203d142f1ed154a4b64ce5cb
![example3](https://user-images.githubusercontent.com/2313757/206842909-6ecf8579-79a7-4567-9226-ef9c2ac6ed45.png)

Thanks

**Comment by brentonv** [comment]
Hi @ratul16 thanks for replying, I've attached some screenshots to better explain what's happening and hopefully you can tell me what I'm doing wrong?

https://medium.com/feed/@ratul16
![example1](https://user-images.githubusercontent.com/2313757/206842910-18df8ac5-6e41-4976-bce7-3f7adcde4cbe.png)

https://www.feedforall.com/sample.xml
![example2](https://user-images.githubusercontent.com/2313757/206842908-591c8dbb-7886-4748-ae4d-d790599a3adb.png)

https://rss.uptimerobot.com/u1547170-7f480a74203d142f1ed154a4b64ce5cb
![example3](https://user-images.githubusercontent.com/2313757/206842909-6ecf8579-79a7-4567-9226-ef9c2ac6ed45.png)

Thanks

**Comment by ratul16** [comment]
Hi @brentonv the reason that `https://rss.uptimerobot.com/u1547170-7f480a74203d142f1ed154a4b64ce5cb` isn't working because the **categories** key doesn't have any value (empty array) to it. So changing the filter according to you need or change how you the response data to be will work just fine.

![image](https://user-images.githubusercontent.com/37189467/208206653-696add57-1e90-4d74-be0e-2033a3954720.png)
